name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
jobs:
  Build and deploy:
    runs-on: is2-gitea-runner 
    steps:
      - name: Check out source code
        uses: https://github.com/actions/checkout@v3
        with:
          fetch-depth: "0"

      - name: Generate version
        run: |
          echo "Hello world"   
